### ISSUE TITLE
Show summary in test execution

### ISSUE THREAD

**Issue by kcm1700** [hifive-snu/hifive-test-explorer#36]
list.html just lists the test executions, but we want to see the summary in each of the test executions.

Required informations
- [x] How many tests were passed
- [x] How many tests are there
- [x] Percentage and graphical percentage bar
- [x] Place appropriate marker or label.

**Comment by sim0629** [comment]
8a0e319f25cb8fdc4eefae24f0b4a1c2d1bf6710 It completes first and second bullet.

**Comment by sim0629** [comment]
94194f6f1ce95d58048d9a8c4dd9a721e6a3b704 others
